spring.application.name=korwmswebapp

server.servlet.session.cookie.name=KOR_PDA_JSESSIONID

server.port=8082
# ê°ë° ì ííë¦¿ ìºì ë¹íì±í
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.servlet.session.cookie.max-age=604800

# KOREA DB
spring.datasource.korea.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.korea.jdbc-url=jdbc:log4jdbc:oracle:thin:@218.147.154.81:1521:INBUS
spring.datasource.korea.username=REXERP
spring.datasource.korea.password=INBUS

# MEXICO DB
spring.datasource.usa.jdbc-url=jdbc:log4jdbc:oracle:thin:@45.58.2.218:1521:WBUSA
spring.datasource.usa.username=wbusa
spring.datasource.usa.password=woobo23300usa
spring.datasource.usa.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

spring.datasource.mexico.jdbc-url=jdbc:log4jdbc:oracle:thin:@187.191.63.113:1521:WBMEX
spring.datasource.mexico.username=wbmex
spring.datasource.mexico.password=woobo23300mex
spring.datasource.mexico.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# HikariCP 설정
spring.datasource.hikari.auto-commit=false

# MyBatis ê³µíµ ì¤ì 
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.example.demo

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-response=true
server.servlet.encoding.force-request=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace

logging.level.log4jdbc.log4j2=off
logging.level.root=info
logging.level.jdbc=off
logging.level.jdbc.sqlonly=info
logging.level.jdbc.sqltiming=off
logging.level.jdbc.resultsettable=info
logging.level.jdbc.audit=off
logging.level.jdbc.resultset=off
logging.level.jdbc.connection=off

spring.config.import=optional:classpath:version.properties

# auto restart
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# 정적 리소스(JS/CSS) 브라우저 캐시 비활성화
spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG